### ISSUE TITLE
Remove unnecessary files (env, pycache, etc.)

### ISSUE THREAD

**Issue by ceferisbarov** [NijatZeynalov/experimenteer#3]

**Comment by KananMahammadli** [comment]
environment files are removed and excluded from git in [This PR](https://github.com/NijatZeynalov/experimenteer/pull/4)

**Comment by ceferisbarov** [comment]
You have made two distinct changes to the project. Do you mind splitting this PR into two parts? It would be easier to follow the progress that way. @KananMahammadli

**Comment by KananMahammadli** [comment]
Actually total changes can be categorized in 4 different parts, to avoid creating 4 chained PRs I opened 1. Main problem is, even if PR only contains removal of virtual environment files, it would lead to thousands of file changes. Therefore it would be better to get some comment from author: @NijatZeynalov if PR can be reviewed by ignoring the deletions, or I can create separate PR for that deletion, merge it to main, then synchronize current PR with main.

**Comment by ceferisbarov** [comment]
My suggestion is creating a separate PR for the whole gitignore issue + formatting (back, etc.). Dockerization can be a second PR, and refactoring a third. I don't think this is unreasonable. Diff page contains so much information that browser keeps freezing.

**Comment by KananMahammadli** [comment]
The thing is removal of venv folder will still result in thousands of file changes and cause the github page freezing. The left of changes are either refactoring or standard python best practices which are easy to review. Changes can easily be checked by clicking the commits, each comment will lead to corresponding file changes or locally by ignoring the deletions.

**Comment by ceferisbarov** [comment]
I am quite aware of that. Changes are both (1) large and (2) functionally independent. If that does not necessitate different PRs, then I don't know what does.

**Comment by KananMahammadli** [comment]
I totally understand your point, main related part is refactoring and dockerizing, so that I could be sure everything works completely, first 2 parts: removing of unnecessary files, and linitng were rather simple. Therefore I didn't bother them, in any case, I am closing current PR, and creating 4 new ones. Thanks for your views.

**Comment by ceferisbarov** [comment]
Thanks. In any case, let's wait for @NijatZeynalov's input.

**Comment by KananMahammadli** [comment]
Issue solved [Here](https://github.com/NijatZeynalov/experimenteer/pull/5)
